<?php

/* @var $this \FrankVerhoeven\Bootstrap\Renderer\PhpRenderer */

/* @var $element \Zend\Form\ElementInterface */
$element = $this->element;

/* @var string $label */
$label = $this->label;

/* @var array $labelAttributes */
$labelAttributes = $this->labelAttributes;

/* @var string $labelPosition (prepend, append) */
$labelPosition = $this->labelPosition;

/* @var bool $renderErrors */
$renderErrors = $this->renderErrors;

?>
<div class="custom-file<?php if (\strstr($element->getAttribute('class'), 'hidden')) echo ' hidden'; ?>">
    <input type="file" class="custom-file-input" id="customFileLang" lang="es">
    <label class="custom-file-label" for="customFileLang">Seleccionar Archivo</label>
    <?= $this->formElement($element); ?>
    <?php if ($label) echo $this->formLabel($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>
