<?php

/* @var $element \Zend\Form\ElementInterface */
$element = $this->element;

/* @var string $label */
$label = $this->label;

/* @var array $labelAttributes */
$labelAttributes = $this->labelAttributes;

/* @var string $labelPosition (prepend, append) */
$labelPosition = $this->labelPosition;

/* @var boolean $renderErrors */
$renderErrors = $this->renderErrors;


?>
<div class="custom-control custom-checkbox">
    <?= $this->formElement($element); ?>
    <label class="custom-control-label pt-1" for="remember">
        <?php if ($label) echo $this->formLabel($element); ?>
    </label>
</div>
