<ul class="navbar-nav">
    <?php foreach ($this->container as $page) :
        /* @var $page Zend\Navigation\Page\AbstractPage */

        // when using partials we need to manually check for ACL conditions
        if (!$this->navbarNav()->accept($page)) continue; ?>

        <?php if (!$page->hasPages()) : ?>

            <li class="nav-item<?php if ($page->isActive()) echo ' active'; ?>">
                <a class="nav-link" href="<?= $page->getHref(); ?>">
                    <?= $this->translate($page->getLabel()); ?>
                </a>
            </li>

        <?php else: ?>

            <?php
            $active = false;

            if ($page->isActive()) {
                $active = true;
            } else {
                $pages = $page->getPages();

                do {
                    if (current($pages)->isActive()) {
                        $active = true;
                    }
                } while (!$active && next($pages));
            }
            ?>

            <li class="nav-item dropdown<?php if ($active) echo ' active'; ?>">
                <a class="nav-link dropdown-toggle" href="<?= $page->getHref(); ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?= $this->translate($page->getLabel()); ?>
                </a>

                <div class="dropdown-menu">
                    <?php foreach ($page->getPages() as $child) :
                        /* @var $child Zend\Navigation\Page\AbstractPage */

                        if(!$this->navbarNav()->accept($child)) continue; ?>

                            <a href="<?= $child->getHref(); ?>" class="dropdown-item<?php if ($child->isActive()) echo ' active'; ?>">
                                <?= $this->translate($child->getLabel()); ?>
                            </a>

                    <?php endforeach; ?>
                </div>
            </li>

        <?php endif; ?>
    <?php endforeach; ?>
</ul>
